name: CI/CD Pipeline

on:
  push:
    branches: [ main ] # Срабатывает при пуше в main

jobs:
  build_and_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my_project_web:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my_project_frontend:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build_and_push # Ждем окончания сборки
    steps:
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/projects/my_project1
            # Обновляем код (если изменился docker-compose.yml)
            git pull origin main
            # Подтягиваем новые образы
            sudo docker compose pull
            # Перезапускаем контейнеры
            sudo docker compose up -d
            # Выполняем миграции и статику
            sudo docker compose exec web python manage.py migrate --noinput
            sudo docker compose exec web python manage.py collectstatic --noinput
